In [1]:
x = 1
type(x)

int

In [2]:
x = 'A'
type(x)

str

In [ ]:
1+2

3

In [ ]:
c = a * b

In [ ]:
import numpy as np
a = np.array([1, 2, 3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
b = np.array([4, 5, 6])
print(b)

[4 5 6]


In [ ]:
c = a*b
print(c)

[ 4 10 18]


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])

In [ ]:
df.head()

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df.describe()

a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df['a'].value_counts()

7    1
1    1
4    1
Name: a, dtype: int64

In [ ]:
df['a'].value_counts().sort_index(ascending=True)

1    1
4    1
7    1
Name: a, dtype: int64

In [3]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3],[11, 12, 13]] # 2개의 샘플, 3개의 특성
y = [0, 1]                      # 각 샘플의 클래스
clf.fit(X, y)

RandomForestClassifier(random_state=0)

In [4]:
clf.predict([[4, 5, 6], [14, 15, 16]])  # 새로운 데이터셋의 클래스를 예측

array([0, 1])